AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Astras API - Kid, Caregiver, and Star Transaction Services

Globals:
  Function:
    Timeout: 30
    Runtime: provided.al2
    Architectures:
      - x86_64
    Environment:
      Variables:
        STAGE: local
        ENVIRONMENT: local
        LOG_LEVEL: DEBUG

Resources:
  # Kid Service API Gateway and Lambda
  KidServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  KidFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/kid-service/
      Handler: bootstrap
      Environment:
        Variables:
          DB_HOST: astras-postgres
          DB_PORT: "5432"
          DB_NAME: astras
          DB_USER: postgres
          DB_PASSWORD: password
          DB_SSL_MODE: disable
      Events:
        GetAllKids:
          Type: Api
          Properties:
            RestApiId: !Ref KidServiceApi
            Path: /kids
            Method: GET
        CreateKid:
          Type: Api
          Properties:
            RestApiId: !Ref KidServiceApi
            Path: /kids
            Method: POST
        GetKidById:
          Type: Api
          Properties:
            RestApiId: !Ref KidServiceApi
            Path: /kids/{id}
            Method: GET
        UpdateKid:
          Type: Api
          Properties:
            RestApiId: !Ref KidServiceApi
            Path: /kids/{id}
            Method: PUT
        DeleteKid:
          Type: Api
          Properties:
            RestApiId: !Ref KidServiceApi
            Path: /kids/{id}
            Method: DELETE

  # Caregiver Service API Gateway and Lambda
  CaregiverServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  CaregiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/caregiver-service/
      Handler: bootstrap
      Environment:
        Variables:
          DB_HOST: astras-postgres
          DB_PORT: "5432"
          DB_NAME: astras
          DB_USER: postgres
          DB_PASSWORD: password
          DB_SSL_MODE: disable
      Events:
        GetAllCaregivers:
          Type: Api
          Properties:
            RestApiId: !Ref CaregiverServiceApi
            Path: /caregivers
            Method: GET
        CreateCaregiver:
          Type: Api
          Properties:
            RestApiId: !Ref CaregiverServiceApi
            Path: /caregivers
            Method: POST
        GetCaregiverById:
          Type: Api
          Properties:
            RestApiId: !Ref CaregiverServiceApi
            Path: /caregivers/{id}
            Method: GET
        UpdateCaregiver:
          Type: Api
          Properties:
            RestApiId: !Ref CaregiverServiceApi
            Path: /caregivers/{id}
            Method: PUT
        DeleteCaregiver:
          Type: Api
          Properties:
            RestApiId: !Ref CaregiverServiceApi
            Path: /caregivers/{id}
            Method: DELETE
        ValidateEmail:
          Type: Api
          Properties:
            RestApiId: !Ref CaregiverServiceApi
            Path: /validate/email
            Method: POST
        ValidateRelationship:
          Type: Api
          Properties:
            RestApiId: !Ref CaregiverServiceApi
            Path: /validate/relationship
            Method: POST

  # Star Service API Gateway and Lambda
  StarServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  StarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/star-service/
      Handler: bootstrap
      Environment:
        Variables:
          DB_HOST: astras-postgres
          DB_PORT: "5432"
          DB_NAME: astras
          DB_USER: postgres
          DB_PASSWORD: password
          DB_SSL_MODE: disable
      Events:
        GetAllTransactions:
          Type: Api
          Properties:
            RestApiId: !Ref StarServiceApi
            Path: /transactions
            Method: GET
        CreateTransaction:
          Type: Api
          Properties:
            RestApiId: !Ref StarServiceApi
            Path: /transactions
            Method: POST
        GetTransactionById:
          Type: Api
          Properties:
            RestApiId: !Ref StarServiceApi
            Path: /transactions/{id}
            Method: GET
        UpdateTransaction:
          Type: Api
          Properties:
            RestApiId: !Ref StarServiceApi
            Path: /transactions/{id}
            Method: PUT
        DeleteTransaction:
          Type: Api
          Properties:
            RestApiId: !Ref StarServiceApi
            Path: /transactions/{id}
            Method: DELETE
        ValidateTransactionType:
          Type: Api
          Properties:
            RestApiId: !Ref StarServiceApi
            Path: /validate/type
            Method: POST
        ValidateAmount:
          Type: Api
          Properties:
            RestApiId: !Ref StarServiceApi
            Path: /validate/amount
            Method: POST

Outputs:
  KidServiceApi:
    Description: "API Gateway endpoint URL for Kid Service"
    Value: !Sub "https://${KidServiceApi}.execute-api.${AWS::Region}.amazonaws.com/local/"
    
  KidServiceApiLocal:
    Description: "Local API Gateway endpoint URL for Kid Service"
    Value: "http://localhost:3000/"

  CaregiverServiceApi:
    Description: "API Gateway endpoint URL for Caregiver Service"
    Value: !Sub "https://${CaregiverServiceApi}.execute-api.${AWS::Region}.amazonaws.com/local/"
    
  CaregiverServiceApiLocal:
    Description: "Local API Gateway endpoint URL for Caregiver Service"
    Value: "http://localhost:3001/"

  StarServiceApi:
    Description: "API Gateway endpoint URL for Star Service"
    Value: !Sub "https://${StarServiceApi}.execute-api.${AWS::Region}.amazonaws.com/local/"
    
  StarServiceApiLocal:
    Description: "Local API Gateway endpoint URL for Star Service"
    Value: "http://localhost:3002/"