services:
  # Dozzle - Simple log viewer for Docker containers
  dozzle:
    image: amir20/dozzle:latest
    container_name: astras-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../logs:/logs:ro
    ports:
      - "8080:8080"
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
    networks:
      - astras-logging

  # Log file viewer using simple nginx
  log-viewer:
    image: nginx:alpine
    container_name: astras-log-viewer
    volumes:
      - ../logs:/usr/share/nginx/html/logs:ro
      - ./nginx-logs.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - astras-logging

networks:
  astras-logging:
    external: true